### ISSUE TITLE
大佬，sql脚本能否提供下呢

### ISSUE THREAD

**Issue by xiaonannet** [gzqnb/netty-32960#1]

**Comment by gzqnb** [comment]
不好意思涉及隐私

**Comment by marionlxy** [comment]
大佬，客户端连接国家平台的能否共享一下呢，处理不好同国家平台的连接，请喝杯咖啡呢

**Comment by gzqnb** [comment]
> 

请看server.java

**Comment by gzqnb** [comment]
> 大佬，客户端连接国家平台的能否共享一下呢，处理不好同国家平台的连接，请喝杯咖啡呢
请看server.java
